[providers]
  php = "8.2"

[phases.setup]
  nixPkgs = ['php82', 'php82Packages.composer', 'nodejs_20', 'npm']

[phases.build]
  cmds = [
    'mkdir -p storage/framework/views storage/framework/cache/data storage/framework/sessions storage/logs bootstrap/cache',
    'composer install --optimize-autoloader --no-dev',
    'npm install',
    'npm run build'
  ]

[start]
  cmd = 'php artisan serve --host=0.0.0.0 --port=$PORT'
